---
driver:
  name: docker
  binary: docker.io
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  #require_chef_omnibus: true

platforms:
  - name: ubuntu
    run_list:
      - "recipe[apt]"

suites:
  - name: server
    data_bags_path: "test/integration/server/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/server/encrypted_data_bag_secret"
    run_list:
      - recipe[sdinc-rundeck::default]
    attributes:
      java: 
        jdk_version: '8'
        oracle:
          accept_oracle_download_terms: true
      rundeck:
        hostname: 'localhost:8080'
